/*
 * LTD2ApiV2
 *
 * This is the official Legion TD 2 public API. The new API endpoint is https://apiv2.legiontd2.com/ <br /> You can generate your key at <a href='https://developer.legiontd2.com/'>developer.legiontd2.com</a><br />In your requests add the HTTP header 'x-api-key' and your secret key from the developer portal. <br /><br />For icons, emotes or splash art images you can use our CDN: <a href='https://cdn.legiontd2.com/icons/Yozora.png'>cdn.legiontd2.com</a>. <br /> If you prefer to host the icons on your own server you can find the image files in your game files: 'Steam\\steamapps\\common\\Legion TD 2\\Legion TD 2_Data\\uiresources\\AeonGT\\hud\\img\\icons'<br /> <br /> The current limits are 15 requests per second / 10k burst requests and a maximum of 10k requests per day. If you need a higher limit, reach out to us in discord or through our support portal. <br /> <br /> If you have any other questions, feel free to ask in the &#35;api channel on the <a href='https://discord.gg/4K4xwCz2DN'>Legion TD 2 Contributors Discord</a>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace TaF.LegionTD2Api.Model;

/// <summary>
///     Player
/// </summary>
[DataContract]
public class Player : IEquatable<Player>, IValidatableObject
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="Player" /> class.
    /// </summary>
    [JsonConstructorAttribute]
    protected Player() { }

    /// <summary>
    ///     Initializes a new instance of the <see cref="Player" /> class.
    /// </summary>
    /// <param name="id">id (required).</param>
    /// <param name="name">name (required).</param>
    /// <param name="avatarUrl">avatarUrl.</param>
    /// <param name="guildTag">guildTag.</param>
    /// <param name="guildName">guildName.</param>
    /// <param name="guildAvatar">guildAvatar.</param>
    public Player(string id = default, string name = default, string avatarUrl = default, string guildTag = default, string guildName = default, string guildAvatar = default)
    {
        // to ensure "id" is required (not null)
        if (id == null)
        {
            throw new InvalidDataException("id is a required property for Player and cannot be null");
        }

        Id = id;

        // to ensure "name" is required (not null)
        if (name == null)
        {
            throw new InvalidDataException("name is a required property for Player and cannot be null");
        }

        Name = name;

        AvatarUrl = avatarUrl;
        GuildTag = guildTag;
        GuildName = guildName;
        GuildAvatar = guildAvatar;
    }

    /// <summary>
    ///     Gets or Sets Id
    /// </summary>
    [DataMember(Name = "_id", EmitDefaultValue = true)]
    public string Id { get; set; }

    /// <summary>
    ///     Gets or Sets Name
    /// </summary>
    [DataMember(Name = "PlayerName", EmitDefaultValue = true)]
    public string Name { get; set; }

    /// <summary>
    ///     Gets or Sets AvatarUrl
    /// </summary>
    [DataMember(Name = "avatarUrl", EmitDefaultValue = false)]
    public string AvatarUrl { get; set; }

    /// <summary>
    ///     Gets or Sets GuildTag
    /// </summary>
    [DataMember(Name = "guildTag", EmitDefaultValue = false)]
    public string GuildTag { get; set; }

    /// <summary>
    ///     Gets or Sets GuildName
    /// </summary>
    [DataMember(Name = "guildName", EmitDefaultValue = false)]
    public string GuildName { get; set; }

    /// <summary>
    ///     Gets or Sets GuildAvatar
    /// </summary>
    [DataMember(Name = "guildAvatar", EmitDefaultValue = false)]
    public string GuildAvatar { get; set; }

    /// <summary>
    ///     Returns true if Player instances are equal
    /// </summary>
    /// <param name="input">Instance of Player to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(Player input)
    {
        if (input == null)
        {
            return false;
        }

        return (Id == input.Id || (Id != null && Id.Equals(input.Id))) && (Name == input.Name || (Name != null && Name.Equals(input.Name))) && (AvatarUrl == input.AvatarUrl || (AvatarUrl != null && AvatarUrl.Equals(input.AvatarUrl))) && (GuildTag == input.GuildTag || (GuildTag != null && GuildTag.Equals(input.GuildTag))) && (GuildName == input.GuildName || (GuildName != null && GuildName.Equals(input.GuildName))) && (GuildAvatar == input.GuildAvatar || (GuildAvatar != null && GuildAvatar.Equals(input.GuildAvatar)));
    }

    /// <summary>
    ///     To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }

    /// <summary>
    ///     Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class Player {\n");
        sb.Append("  Id: ").Append(Id).Append("\n");
        sb.Append("  Name: ").Append(Name).Append("\n");
        sb.Append("  AvatarUrl: ").Append(AvatarUrl).Append("\n");
        sb.Append("  GuildTag: ").Append(GuildTag).Append("\n");
        sb.Append("  GuildName: ").Append(GuildName).Append("\n");
        sb.Append("  GuildAvatar: ").Append(GuildAvatar).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    ///     Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    ///     Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return Equals(input as Player);
    }

    /// <summary>
    ///     Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            if (Id != null)
            {
                hashCode = hashCode * 59 + Id.GetHashCode();
            }

            if (Name != null)
            {
                hashCode = hashCode * 59 + Name.GetHashCode();
            }

            if (AvatarUrl != null)
            {
                hashCode = hashCode * 59 + AvatarUrl.GetHashCode();
            }

            if (GuildTag != null)
            {
                hashCode = hashCode * 59 + GuildTag.GetHashCode();
            }

            if (GuildName != null)
            {
                hashCode = hashCode * 59 + GuildName.GetHashCode();
            }

            if (GuildAvatar != null)
            {
                hashCode = hashCode * 59 + GuildAvatar.GetHashCode();
            }

            return hashCode;
        }
    }
}